### ISSUE TITLE
Resnet-18 example on host fails to compile the model

### ISSUE THREAD

**Issue by denishem** [Xilinx/pyxir#60]
Hi,

I'm trying to use TVM on the ZCU102. I successfully compiled a PYNQ image and a PYNQ DPU for the ZCU102. I also managed to set up the environment for Vitis AI, TVM and PyXIR on host (Ubuntu 20.04) but when running the Resnet-18 example on host I'm getting the following error, (I know it shows ZCU104 but I'm getting the same error by changing the target):
```
********************* Quantization Summary *********************      
INFO: Output:       
  quantize_eval_model: /tmp/tmpqe35e808/quantize_eval_model.pb       
  deploy_model: /tmp/tmpqe35e808/deploy_model.pb
Segmentation fault (core dumped)
Traceback (most recent call last):
  File "edge_resnet_18_host.py", line 219, in <module>
    InferenceSession.run()
  File "/workspace/tvm/python/tvm/contrib/graph_executor.py", line 206, in run
    self._run()
  File "tvm/_ffi/_cython/./packed_func.pxi", line 323, in tvm._ffi._cy3.core.PackedFuncBase.__call__
  File "tvm/_ffi/_cython/./packed_func.pxi", line 257, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./packed_func.pxi", line 246, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 163, in tvm._ffi._cy3.core.CALL
tvm._ffi.base.TVMError: AssertionError: Can't retrieve right out tensor names from DNNC compiler output
At:
  /home/vitis-ai-user/.local/lib/python3.6/site-packages/pyxir-0.3.0-py3.6-linux-x86_64.egg/pyxir/contrib/target/components/DPUCZDX8G/vai_c_dnnc.py(164): compile
  /home/vitis-ai-user/.local/lib/python3.6/site-packages/pyxir-0.3.0-py3.6-linux-x86_64.egg/pyxir/contrib/target/components/DPUCZDX8G/zcu104.py(77): xgraph_dpu_zcu104_compiler
  /home/vitis-ai-user/.local/lib/python3.6/site-packages/pyxir-0.3.0-py3.6-linux-x86_64.egg/pyxir/base.py(156): compile
  /home/vitis-ai-user/.local/lib/python3.6/site-packages/pyxir-0.3.0-py3.6-linux-x86_64.egg/pyxir/base.py(208): compile_opaque_func
  /home/vitis-ai-user/.local/lib/python3.6/site-packages/pyxir-0.3.0-py3.6-linux-x86_64.egg/pyxir/opaque_func.py(113): opaque_func_wrapper
  /workspace/tvm/python/tvm/contrib/graph_executor.py(206): run
  edge_resnet_18_host.py(219): <module>
```
I carefully followed https://tvm.apache.org/docs/deploy/vitis_ai.html#vitis-ai-integration multiple times with the same error at the end.

**Comment by jtuyls** [comment]
Hi @denishem, I think this is caused by the DNNC/DNNDK  Zynq flow being deprecated with Vitis AI 1.4 in favor of the VART flow. We are in the process of creating a PR to update the TVM documentation for this. There are two options tor proceed for now:

- Follow the latest instructions here (Vitis AI 1.4): https://github.com/Xilinx/Vitis-AI/tree/master/external/tvm
- Follow the TVM instructions (https://tvm.apache.org/docs/deploy/vitis_ai.html#vitis-ai-integration) with pyxir v0.2.1 and Vitis AI docker version 1.3.598.
